version: '3.9'
services:
  postgres:
    image: postgres
    container_name: banco_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 553322@@##
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: banco_sqlserver
    environment:
      SA_PASSWORD: 553322@@##
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver:/var/opt/mssql/data